# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Los Angeles Pokemon Go
email: info@losangelespokemongo.com
description: Domain available
url: http://losangelespokemongo.com

# Meta variable for Google Webmaster tools
google-verification: AF2Wo7MkjoDe3fwejuzq2W5f2PzhyQED5lL7he5Pjhs

exclude:
    - LICENSE
    - README.md
    - CNAME
    - archive

# Build settings
markdown: kramdown
highlighter: rouge
